# -*- coding: utf-8 -*-
"""24-09-04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gD1dIczLmBAmSLXjY_G1eIdBf1vZFSmF
"""

print("Hello World")

print("Hello python")

print("수많은 갈매기들의 기침","배고프다")

import pylab as py

x_deg = py.arange(-180, 180+1)
x_red = py.deg2rad(x_deg)
y = py.sin(x_red)

py.plot(x_deg, y)

py.xlabel('x (deg)')
py.ylabel('sin(x)')
py.grid(True)